version: '3.3'

services:
  db:
    image: mysql
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - wordpress-network
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    depends_on: 
      - db
    image: bruiglesias/flask-image
    ports:
      - "5000:5000"
    restart: always
    networks: 
      - wordpress-network

networks:
  wordpress-network: