version: '3.3'

services:
  db: 
    image: mysql:5.7
    ports:
      - 3306:3306 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - wordpress-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - wordpress-network

volumes:
  db_data: {}

networks:
  backend:
    driver: wordpress-network